build: improve pulling of protos
Signed-off-by: Brandon McAnsh <git@bmcreations.dev>

diff --git a/Scripts/pull_protos b/Scripts/pull_protos
--- a/Scripts/pull_protos
+++ b/Scripts/pull_protos
@@ -4,53 +4,70 @@
 # Exit if any command fails
 set -e
 
-REPO_NAME="$1"
-BRANCH="$2"
-DESTINATION_PATH="$3"
+#!/bin/bash
 
-if [ ! -d "$DESTINATION_PATH" ]
-then
-  echo "No destination directory provided."
-  exit
-fi
+root=$(pwd)
+REPO_URL="git@github.com:code-payments/code-protobuf-api.git"  # Default repo URL
+COMMIT_SHA=""
+TEMP_DIR=$(mktemp -d)
+TARGET="code"
+DEST_DIR_PACKAGE="CodeAPI"
 
-GIT_TEMP_PATH=$(mktemp -d -t "${REPO_NAME/\//_}")
-TEMP_DIR="$DESTINATION_PATH/.temp"
-
-mkdir -p $TEMP_DIR
-
-# =============================
-# Register the cleanup function 
-# to be called on EXIT signal
-
-function cleanup {
-  echo "Cleaning up..."
-  rm -rf ${GIT_TEMP_PATH}
-  rm -rf ${TEMP_DIR}
-  echo "Done."
-}
-
-trap cleanup EXIT
-
-# ==================
-# Clone repositories
-
-echo "Cloning '${REPO_NAME}'..."
-git clone -b ${BRANCH} --single-branch "git@github.com:${REPO_NAME}.git" ${GIT_TEMP_PATH}
-
-# ================================
-# Generate protos
-
-echo "Importing protos in '${GIT_TEMP_PATH}'..."
-
-for path in $(find ${GIT_TEMP_PATH} -name '*.proto' | xargs -0 -n1); do
-  PROTO_PATH="${path/$GIT_TEMP_PATH\//}"
-  DST_DIR="${DESTINATION_PATH}/${PROTO_PATH}"
-  
-  mkdir -p "$(dirname $DST_DIR)"
-  cp -rf ${path} ${DST_DIR}
-
-  echo "Copied ${DST_DIR}"
+# Parse options
+while getopts ":r:t" opt; do
+  case ${opt} in
+    r )
+      REPO_URL=$OPTARG
+      ;;
+    t )
+      TARGET=$OPTARG
+      if [ "$TARGET" == "flipchat" ]; then
+        DEST_DIR_PACKAGE="FlipchatAPI"
+        REPO_URL="git@github.com:code-payments/flipchat-protobuf-api.git"
+      elif [ "$TARGET" == "flipcash" ]; then
+        DEST_DIR_PACKAGE="FlipcashAPI"
+        REPO_URL="git@github.com:code-payments/flipcash-protobuf-api.git"
+      fi
+      ;;
+    \? )
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+  esac
 done
 
-echo "Done."
+shift $((OPTIND -1))
+
+DEST_DIR="$DEST_DIR_PACKAGE/Sources/$DEST_DIR_PACKAGE/proto"
+
+# Get the commit SHA if provided
+COMMIT_SHA=$1
+
+# Clone the repository
+git clone "$REPO_URL" "$TEMP_DIR"
+
+# Change to the cloned repository directory
+cd "$TEMP_DIR" || exit
+
+# If a commit SHA is provided, checkout that commit
+if [ -n "$COMMIT_SHA" ]; then
+    git checkout "$COMMIT_SHA"
+else
+    git checkout main
+fi
+
+# Create the destination directory if it doesn't exist
+mkdir -p "${root}/$DEST_DIR"
+
+# Copy proto files
+if [ -d "proto" ]; then
+    rsync -av --exclude='buf*' proto/ "${root}/$DEST_DIR/"
+    echo "Proto files copied successfully."
+else
+    echo "Error: 'proto' directory not found in the repository."
+    exit 1
+fi
+
+# Clean up: remove the temporary directory
+cd ../..
+rm -rf "$TEMP_DIR"
